# Database settings.
database:
  driverClass: org.postgresql.Driver
  user: blms
  password: blms
  url: jdbc:postgresql://localhost:5432/blms
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  maxWaitForConnection: 1s
  validationQuery: "/* MyApplication Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false

server:
  #  softNofileLimit: 1000
  #  hardNofileLimit: 1000
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
# Logging settings.
logging:
  level: INFO
  loggers:
    com.blms: DEBUG
  appenders:
    - type: console
#    - type: file
#      threshold: INFO
#      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
#      currentLogFilename: /tmp/application.log
#      archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}-%i.log.gz
#      archivedFileCount: 7
#      timeZone: UTC
#      maxFileSize: 10MiB

# the key needs to match the configuration key of the renderer (ViewRenderer::getConfigurationKey)
#viewRendererConfiguration:
#  freemarker:
#    strict_syntax: yes
#    whitespace_stripping: yes

#metrics:
#  reporters:
#    - type: graphite
#      host: localhost
#      port: 2003
#      prefix: example
#      frequency: 1m
